// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication1.Infrastructure;

#nullable disable

namespace BackendTeaTech.Migrations
{
    [DbContext(typeof(ConnectionContext))]
    [Migration("20240315182410_edição-nomes-colunas")]
    partial class ediçãonomescolunas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.ChildAssisted", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aversions")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aversions");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<string>("FoodSelectivity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("food_selectiity");

                    b.Property<string>("MedicalRecord")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("medical_record");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Photo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("photo");

                    b.Property<string>("Preferences")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("preferences");

                    b.Property<Guid?>("fk_responsible_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("fk_responsible_id");

                    b.ToTable("child_assisted");
                });

            modelBuilder.Entity("WebApplication1.Models.Responsible", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("NameResponsibleOne")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_responsible_one");

                    b.Property<string>("NameResponsibleTwo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_responsible_two");

                    b.Property<string>("ResponsibleCpfOne")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("responsible_cpf_one");

                    b.Property<string>("ResponsibleCpfTwo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("resposible_cpf_two");

                    b.Property<string>("ResponsibleKinshipOne")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("responsible_kinship_one");

                    b.Property<string>("ResponsibleKinshipTwo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("responsible_kinship_two");

                    b.Property<Guid?>("fk_user_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("fk_user_id");

                    b.ToTable("responsible");
                });

            modelBuilder.Entity("WebApplication1.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("WebApplication1.Models.ChildAssisted", b =>
                {
                    b.HasOne("WebApplication1.Models.Responsible", "Responsible")
                        .WithMany()
                        .HasForeignKey("fk_responsible_id");

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("WebApplication1.Models.Responsible", b =>
                {
                    b.HasOne("WebApplication1.User", "User")
                        .WithMany()
                        .HasForeignKey("fk_user_id");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
